# Generated by Django 2.2.5 on 2019-11-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20191128_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
